version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  minio:
    image: minio/minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:${REDIS_PORT}
      MINIO_URL: http://minio:${MINIO_PORT}
    depends_on:
      - postgres
      - redis
      - minio

  worker:
    build:
      context: ./apps/worker
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:${REDIS_PORT}
      MINIO_URL: http://minio:${MINIO_PORT}
    depends_on:
      - redis
      - postgres
      - minio

  docs:
    build:
      context: ./apps/docs
    ports:
      - "${DOCS_PORT}:4000"
    depends_on:
      - postgres

volumes:
  pgdata:
  minio_data:
