services:
  frontend:
    build:
      dockerfile: apps/frontend/Dockerfile
      context: .
      args:
        AUTH_SECRET: ${AUTH_SECRET}
        DISCOLAIRE_API_KEY: ${DISCOLAIRE_API_KEY}
        RESEND_API_KEY: ${RESEND_API_KEY}
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
        S3_REGION: ${S3_REGION}
        S3_BUCKET_NAME: ${S3_BUCKET_NAME}
        S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
        S3_AVATAR_BUCKET_NAME: ${S3_AVATAR_BUCKET_NAME}
        S3_IMAGE_BUCKET_NAME: ${S3_IMAGE_BUCKET_NAME}
        S3_DOCUMENT_BUCKET_NAME: ${S3_DOCUMENT_BUCKET_NAME}
        NEXT_PUBLIC_DEPLOYMENT_ENV: ${NEXT_PUBLIC_DEPLOYMENT_ENV}
        MESSAGING_SERVICE_URL: ${MESSAGING_SERVICE_URL}
        WHATSAPP_VERIFY_TOKEN: ${WHATSAPP_VERIFY_TOKEN}
        WHATSAPP_API_TOKEN: ${WHATSAPP_API_TOKEN}
        MESSAGING_SECRET_KEY: ${MESSAGING_SECRET_KEY}
        WHATSAPP_BUSINESS_PHONE_NUMBER_ID: ${WHATSAPP_BUSINESS_PHONE_NUMBER_ID}
        REDIS_URL: ${REDIS_URL}
        NOVU_API_KEY: ${NOVU_API_KEY}
        SUPER_ADMIN_USERNAME: ${SUPER_ADMIN_USERNAME}
        NEXT_PUBLIC_MINIO_URL: ${NEXT_PUBLIC_MINIO_URL}
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
      DISCOLAIRE_API_KEY: ${DISCOLAIRE_API_KEY}
      RESEND_API_KEY: ${RESEND_API_KEY}
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      WHATSAPP_BUSINESS_PHONE_NUMBER_ID: ${WHATSAPP_BUSINESS_PHONE_NUMBER_ID}
      S3_REGION: ${S3_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_AVATAR_BUCKET_NAME: ${S3_AVATAR_BUCKET_NAME}
      S3_IMAGE_BUCKET_NAME: ${S3_IMAGE_BUCKET_NAME}
      S3_DOCUMENT_BUCKET_NAME: ${S3_DOCUMENT_BUCKET_NAME}
      WHATSAPP_VERIFY_TOKEN: ${WHATSAPP_VERIFY_TOKEN}
      WHATSAPP_API_TOKEN: ${WHATSAPP_API_TOKEN}
      NOVU_API_KEY: ${NOVU_API_KEY}
      NEXT_PUBLIC_DEPLOYMENT_ENV: ${NEXT_PUBLIC_DEPLOYMENT_ENV}
      MESSAGING_SERVICE_URL: ${MESSAGING_SERVICE_URL}
      MESSAGING_SECRET_KEY: ${MESSAGING_SECRET_KEY}
      REDIS_URL: ${REDIS_URL}
      SUPER_ADMIN_USERNAME: ${SUPER_ADMIN_USERNAME}
      NEXT_PUBLIC_MINIO_URL: ${NEXT_PUBLIC_MINIO_URL}

    env_file:
      - ./.env
    ports:
      - "3000:3000"
