packages:
  - apps/*
  - packages/*

catalog:
  '@tanstack/react-query': ^5.87.4
  '@trpc/client': ^11.5.1
  '@trpc/server': ^11.5.1
  '@trpc/tanstack-react-query': ^11.5.1
  '@types/react-dom': ^19.1.9
  eslint: ^9.35.0
  prettier: ^3.6.2
  react: 19.1.1
  react-dom: 19.1.1
  tailwindcss: ^3.4.17
  typescript: ^5.9.2
  zod: ^3.25.76

catalogs:
  react19:
    '@types/react': ^19.1.13
    '@types/react-dom': ^19.1.9
    react: 19.1.1
    react-dom: 19.1.1

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
