packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@tanstack/react-query": ^5.69.0
  "@trpc/client": ^11.0.0
  "@trpc/react-query": ^11.0.0
  "@trpc/tanstack-react-query": ^11.0.0
  "@trpc/server": ^11.0.0
  "@types/node": "^22.13.11"
  eslint: ^9.23.0
  prettier: ^3.5.3
  next: "^15.2.3"
  tailwindcss: ^3.4.17
  typescript: ^5.8.2
  zod: ^3.24.2
  react: 19.0.0
  react-dom: 19.0.0
  "@types/react": ^19.0.12
  "@types/react-dom": ^19.0.4
