packages:
  - apps/*
  - packages/*

catalog:
  '@tanstack/react-query': ^5.90.2
  '@trpc/client': ^11.6.0
  '@trpc/server': ^11.6.0
  '@trpc/tanstack-react-query': ^11.6.0
  '@types/react-dom': ^19.2.0
  eslint: ^9.36.0
  prettier: ^3.6.2
  react: 19.2.0
  react-dom: 19.2.0
  tailwindcss: ^3.4.18
  typescript: ^5.9.3
  zod: ^3.25.76

catalogs:
  react19:
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    react: 19.2.0
    react-dom: 19.2.0

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
