packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.59.16
  "@trpc/client": ^11.0.0-rc.593
  "@trpc/react-query": ^11.0.0-rc.593
  "@trpc/server": ^11.0.0-rc.593
  eslint: ^9.13.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.5.4
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.1

  react19:
    react: rc
    react-dom: rc
    "@types/react": npm:types-react@rc
    "@types/react-dom": npm:types-react-dom@rc
