packages:
  - apps/*
  - packages/*
catalog:
  "@tanstack/react-query": 5.75.2
  "@trpc/client": ^11.1.2
  "@trpc/react-query": ^11.1.2
  "@trpc/tanstack-react-query": ^11.1.2
  "@trpc/server": ^11.1.2
  "@types/node": ^22.15.3
  eslint: ^9.26.0
  prettier: ^3.5.3
  next: ^15.3.1
  tailwindcss: ^4.1.5
  typescript: ^5.8.3
  zod: ^3.24.4
  react: 19.0.0
  react-dom: 19.0.0
  "@types/react": ~19.1.2
  "@types/react-dom": ^19.1.3
nodeLinker: hoisted
