packages:
  - apps/*
  - packages/*

catalog:
  "@tanstack/react-query": 5.84.0
  "@trpc/client": ^11.4.3
  "@trpc/react-query": ^11.4.3
  "@trpc/tanstack-react-query": ^11.4.3
  "@trpc/server": ^11.4.3
  "@types/node": ^22.17.0
  eslint: ^9.32.0
  framer-motion: 12.23.12
  prettier: ^3.6.2
  next: 15.4.5
  tailwindcss: ^4.1.11
  typescript: ^5.9.2
  zod: 3.25.76
  react: 19.1.1
  react-dom: 19.1.1
  "@types/react": ~19.1.9
  "@types/react-dom": ^19.1.7

nodeLinker: hoisted
