packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@tanstack/react-query": 5.73.3
  "@trpc/client": ^11.1.1
  "@trpc/react-query": ^11.1.1
  "@trpc/tanstack-react-query": ^11.1.1
  "@trpc/server": ^11.1.1
  "@types/node": "^22.15.2"
  eslint: ^9.25.1
  prettier: ^3.5.3
  next: "^15.3.1"
  tailwindcss: ^4.1.4
  typescript: ^5.8.3
  zod: ^3.24.3
  react: 19.1.0
  react-dom: 19.1.0
  "@types/react": ^19.1.2
  "@types/react-dom": ^19.1.2
