packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@tanstack/react-query": ^5.66.11
  "@trpc/client": ^11.0.0-rc.819
  "@trpc/react-query": ^11.0.0-rc.819
  "@trpc/server": ^11.0.0-rc.819
  "@types/node": "^22.13.8"
  eslint: ^9.21.0
  prettier: ^3.5.2
  next: "^15.2.0"
  tailwindcss: ^3.4.17
  typescript: ^5.8.2
  zod: ^3.24.2
  react: 19.0.0
  react-dom: 19.0.0
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
