packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@tanstack/react-query": ^5.72.2
  "@trpc/client": ^11.1.0
  "@trpc/react-query": ^11.1.0
  "@trpc/tanstack-react-query": ^11.1.0
  "@trpc/server": ^11.1.0
  "@types/node": "^22.14.1"
  eslint: ^9.24.0
  prettier: ^3.5.3
  next: "^15.3.0"
  tailwindcss: ^4.1.3
  typescript: ^5.8.3
  zod: ^3.24.2
  react: 19.1.0
  react-dom: 19.1.0
  "@types/react": ^19.1.1
  "@types/react-dom": ^19.1.2
