packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.39.2
  '@tailwindcss/postcss': ^4.1.18
  '@tanstack/react-form': ^1.27.7
  '@tanstack/react-query': ^5.90.16
  '@trpc/client': ^11.8.1
  '@trpc/server': ^11.8.1
  '@trpc/tanstack-react-query': ^11.8.1
  '@types/react-dom': ^19.2.3
  eslint: ^9.39.2
  prettier: ^3.7.4
  react: 19.2.3
  react-dom: 19.2.3
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  zod: ^3.25.76

catalogs:
  react19:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: 19.2.3
    react-dom: 19.2.3

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - msw
  - prisma
  - sharp
  - unrs-resolver

overrides:
  '@types/minimatch': 5.1.2

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
