packages:
  - apps/*
  - packages/*
catalog:
  "@tanstack/react-query": 5.79.0
  "@trpc/client": ^11.1.4
  "@trpc/react-query": ^11.1.4
  "@trpc/tanstack-react-query": ^11.1.4
  "@trpc/server": ^11.1.4
  "@types/node": ^22.15.29
  eslint: ^9.28.0
  prettier: ^3.5.3
  next: ^15.3.3
  tailwindcss: ^4.1.8
  typescript: ^5.8.3
  zod: ^3.25.45
  react: 19.1.0
  react-dom: 19.1.0
  "@types/react": ~19.1.6
  "@types/react-dom": ^19.1.5
nodeLinker: hoisted
