packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@tanstack/react-query": ^5.66.0
  "@trpc/client": ^11.0.0-rc.749
  "@trpc/react-query": ^11.0.0-rc.749
  "@trpc/server": ^11.0.0-rc.749
  "@types/node": "^22.13.5"
  eslint: ^9.20.0
  prettier: ^3.5.0
  next: "^15.1.6"
  tailwindcss: ^3.4.17
  typescript: ^5.7.3
  zod: ^3.24.1
  react: 19.0.0
  react-dom: 19.0.0
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
