packages:
  - apps/*
  - packages/*

catalog:
  '@tanstack/react-query': 5.81.5
  '@trpc/client': ^11.4.3
  '@trpc/react-query': ^11.4.3
  '@trpc/tanstack-react-query': ^11.4.3
  '@trpc/server': ^11.4.3
  '@types/node': ^22.15.34
  eslint: ^9.30.0
  prettier: ^3.6.2
  next: ^15.3.4
  tailwindcss: ^4.1.11
  typescript: ^5.8.3
  zod: ^3.25.67
  react: 19.1.0
  react-dom: 19.1.0
  '@types/react': ~19.1.8
  '@types/react-dom': ^19.1.6

nodeLinker: hoisted
