import {
  BookOpenText,
  BookText,
  Captions,
  Contact,
  FolderOpen,
  HandCoins,
  NotebookPen,
  Printer,
  Proportions,
  Receipt,
  TableProperties,
  Users,
  type LucideIcon,
} from "lucide-react";

export const sidebarIcons: Record<string, LucideIcon> = {
  documents: FolderOpen,
  assignments: NotebookPen,
  gradesheets: BookOpenText,
  fees: Receipt,
  print: Printer,
  enrollments: Users,
  details: TableProperties,
  financial_situation: HandCoins,
  subjects: Captions,
  programs: BookText,
  attendances: Contact,
  report_cards: Proportions,
};
