import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod/v4";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string(),
    MESSAGING_SERVICE_URL: z.string(),
    MESSAGING_SECRET_KEY: z.string(),
    // AWS S3
    AWS_ACCESS_KEY_ID: z.string().min(10),
    AWS_REGION: z.string().min(2),
    AWS_SECRET_ACCESS_KEY: z.string().min(1),
    REDIS_URL: z.string().min(1),
    UNKEY_ROOT_KEY: z.string().optional(),
    AUTH_SECRET: z.string().min(1),
    DISCOLAIRE_API_KEY: z.string().min(1),
    S3_AVATAR_BUCKET_NAME: z.string().min(1),
    RESEND_API_KEY: z.string().min(1),
    SMS_PROVIDER: z.enum(["twilio", "sns", "vonage"]).optional(),
    TWILIO_ACCOUNT_SID: z.string().min(1).optional(),
    TWILIO_AUTH_TOKEN: z.string().min(1).optional(),
    TWILIO_SMS_FROM: z.string().min(1).optional(),
    SNS_ACCESS_KEY_ID: z.string().min(1).optional(),
    SNS_SECRET_ACCESS_KEY: z.string().min(1).optional(),
    SNS_REGION: z.string().min(1).optional(),
    VONAGE_API_KEY: z.string().min(1).optional(),
    VONAGE_API_SECRET: z.string().min(1).optional(),
    VONAGE_SMS_FROM: z.string().min(1).optional(),
    WHATSAPP_API_TOKEN: z.string().min(1).optional(),
    WHATSAPP_BUSINESS_PHONE_NUMBER_ID: z.string().min(1).optional(),
  },
  client: {
    NEXT_PUBLIC_MINIO_URL: z.string().min(1).url(),
    NEXT_PUBLIC_DEPLOYMENT_ENV: z.enum(["local", "cloud"]),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    DISCOLAIRE_API_KEY: process.env.DISCOLAIRE_API_KEY,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    S3_AVATAR_BUCKET_NAME: process.env.S3_AVATAR_BUCKET_NAME,
    MESSAGING_SERVICE_URL: process.env.MESSAGING_SERVICE_URL,
    NEXT_PUBLIC_MINIO_URL: process.env.NEXT_PUBLIC_MINIO_URL,
    MESSAGING_SECRET_KEY: process.env.MESSAGING_SECRET_KEY,
    REDIS_URL: process.env.REDIS_URL,
    NEXT_PUBLIC_DEPLOYMENT_ENV: process.env.NEXT_PUBLIC_DEPLOYMENT_ENV,
    UNKEY_ROOT_KEY: process.env.UNKEY_ROOT_KEY,
    AUTH_SECRET: process.env.AUTH_SECRET,
    SMS_PROVIDER: process.env.SMS_PROVIDER,
    TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
    TWILIO_SMS_FROM: process.env.TWILIO_SMS_FROM,
    SNS_ACCESS_KEY_ID: process.env.SNS_ACCESS_KEY_ID,
    SNS_SECRET_ACCESS_KEY: process.env.SNS_SECRET_ACCESS_KEY,
    SNS_REGION: process.env.SNS_REGION,
    VONAGE_API_KEY: process.env.VONAGE_API_KEY,
    VONAGE_API_SECRET: process.env.VONAGE_API_SECRET,
    VONAGE_SMS_FROM: process.env.VONAGE_SMS_FROM,
    WHATSAPP_API_TOKEN: process.env.WHATSAPP_API_TOKEN,
    WHATSAPP_BUSINESS_PHONE_NUMBER_ID:
      process.env.WHATSAPP_BUSINESS_PHONE_NUMBER_ID,

    // AWS S3
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_REGION: process.env.AWS_REGION,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  },
  //experimental__runtimeEnv: {},
  skipValidation:
    !!process.env.CI || process.env.npm_lifecycle_event === "lint",
});
