import type { Metadata } from "next";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";

import { Header } from "~/components/header";

import "~/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: [{ media: "(prefers-color-scheme: dark)" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} dark overflow-x-hidden font-sans antialiased`}
      >
        <Header />
        <main className="container mx-auto overflow-hidden px-4 md:overflow-visible">
          {children}
        </main>
      </body>
    </html>
  );
}
