import type { Metadata } from "next";

import { cn } from "@repo/ui/lib/utils";

import { Header } from "~/components/header";
import { fontVariables } from "~/lib/fonts";

import "~/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: [{ media: "(prefers-color-scheme: dark)" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `dark overflow-x-hidden font-sans antialiased`,
          fontVariables,
        )}
      >
        <Header />
        <main className="container mx-auto overflow-hidden px-4 md:overflow-visible">
          {children}
        </main>
      </body>
    </html>
  );
}
