export type RecipientType = "staff" | "student" | "contact";

export interface EmailTemplate {
  key: string; // matches NotificationConfig.templateKey
  name: string;
  description: string;
  category: string;
  enabled: boolean;
  staff: boolean;
  student: boolean;
  contact: boolean;
}

export const EMAIL_CATEGORIES: { key: string; label: string }[] = [
  { key: "0001", label: "Attendance" },
  { key: "0002", label: "Academic" },
  { key: "0003", label: "Behaviour" },
  { key: "0004", label: "Finance" },
  { key: "0005", label: "Health & Wellbeing" },
  { key: "0006", label: "Events & Activities" },
  { key: "0007", label: "Admissions" },
  { key: "0008", label: "Communication" },
  { key: "0009", label: "System & Admin" },
  { key: "0010", label: "Reports" },
];

export type EmailCategory = (typeof EMAIL_CATEGORIES)[number]["label"];

export const EMAIL_TEMPLATES: EmailTemplate[] = [
  // Attendance
  {
    key: "att-001",
    name: "Absence Notification",
    description: "Sent when a student is marked absent for the day.",
    category: "Attendance",
    enabled: true,
    staff: true,
    student: false,
    contact: true,
  },
  {
    key: "att-002",
    name: "Late Arrival Alert",
    description: "Notifies when a student arrives after school start time.",
    category: "Attendance",
    enabled: true,
    staff: true,
    student: false,
    contact: true,
  },
  {
    key: "att-003",
    name: "Attendance Summary (Weekly)",
    description: "Weekly overview of student attendance sent to parents.",
    category: "Attendance",
    enabled: true,
    staff: false,
    student: false,
    contact: true,
  },
  {
    key: "att-004",
    name: "Persistent Absence Warning",
    description:
      "Alert sent when student falls below 90% attendance threshold.",
    category: "Attendance",
    enabled: true,
    staff: true,
    student: false,
    contact: true,
  },
  {
    key: "att-005",
    name: "Authorised Absence Confirmation",
    description: "Confirms that an absence request has been approved.",
    category: "Attendance",
    enabled: true,
    staff: false,
    student: false,
    contact: true,
  },

  // Academic
  {
    key: "aca-001",
    name: "Grade Published",
    description: "Notifies when a teacher publishes results for an assessment.",
    category: "Academic",
    enabled: true,
    staff: false,
    student: true,
    contact: true,
  },
  {
    key: "aca-002",
    name: "Homework Assigned",
    description: "Sent when new homework is set for a class.",
    category: "Academic",
    enabled: true,
    staff: false,
    student: true,
    contact: false,
  },
  {
    key: "aca-003",
    name: "Homework Overdue",
    description: "Reminder that a homework assignment has not been submitted.",
    category: "Academic",
    enabled: true,
    staff: true,
    student: true,
    contact: true,
  },
  {
    key: "aca-004",
    name: "Term Report Released",
    description: "Notifies when the official term report is available online.",
    category: "Academic",
    enabled: true,
    staff: false,
    student: true,
    contact: true,
  },
  {
    key: "aca-005",
    name: "Academic Achievement Award",
    description: "Celebrates a student reaching a notable academic milestone.",
    category: "Academic",
    enabled: true,
    staff: false,
    student: true,
    contact: true,
  },
  {
    key: "aca-006",
    name: "Exam Timetable Published",
    description: "Informs recipients when the exam schedule is finalised.",
    category: "Academic",
    enabled: true,
    staff: true,
    student: true,
    contact: true,
  },

  // Behaviour
  {
    key: "beh-001",
    name: "Behaviour Incident Report",
    description: "Summary of a logged behaviour incident for a student.",
    category: "Behaviour",
    enabled: true,
    staff: true,
    student: false,
    contact: true,
  },
  {
    key: "beh-002",
    name: "Detention Notice",
    description: "Informs parent or guardian that a detention has been issued.",
    category: "Behaviour",
    enabled: true,
    staff: false,
    student: true,
    contact: true,
  },
  {
    key: "beh-003",
    name: "Positive Behaviour Recognition",
    description: "Celebrates positive behaviour or achievement points earned.",
    category: "Behaviour",
    enabled: true,
    staff: false,
    student: true,
    contact: true,
  },
  {
    key: "beh-004",
    name: "Suspension Notice",
    description: "Formal notification of a fixed-term exclusion.",
    category: "Behaviour",
    enabled: true,
    staff: true,
    student: false,
    contact: true,
  },

  // Finance
  {
    key: "fin-001",
    name: "Invoice Generated",
    description: "Sent when a new fee invoice is created for a student.",
    category: "Finance",
    enabled: true,
    staff: false,
    student: false,
    contact: true,
  },
  {
    key: "fin-002",
    name: "Payment Received",
    description:
      "Confirmation email when a payment has been successfully processed.",
    category: "Finance",
    enabled: true,
    staff: false,
    student: false,
    contact: true,
  },
  {
    key: "fin-003",
    name: "Payment Overdue Reminder",
    description: "Reminder that an outstanding balance remains unpaid.",
    category: "Finance",
    enabled: true,
    staff: true,
    student: false,
    contact: true,
  },
  {
    key: "fin-004",
    name: "Trip/Activity Payment Request",
    description:
      "Payment link sent when a student is signed up for a school trip.",
    category: "Finance",
    enabled: true,
    staff: false,
    student: false,
    contact: true,
  },
  {
    key: "fin-005",
    name: "Bursary/Grant Confirmation",
    description:
      "Notifies when a financial support application has been approved.",
    category: "Finance",
    enabled: true,
    staff: true,
    student: false,
    contact: true,
  },

  // Health & Wellbeing
  {
    key: "hlt-001",
    name: "Medical Appointment Reminder",
    description: "Reminder for a scheduled medical or counselling appointment.",
    category: "Health & Wellbeing",
    enabled: true,
    staff: false,
    student: true,
    contact: true,
  },
  {
    key: "hlt-002",
    name: "Medication Administration Notice",
    description: "Informs parents that medication was administered at school.",
    category: "Health & Wellbeing",
    enabled: true,
    staff: true,
    student: false,
    contact: true,
  },
  {
    key: "hlt-003",
    name: "Safeguarding Alert (Internal)",
    description: "Internal notification sent to designated safeguarding leads.",
    category: "Health & Wellbeing",
    enabled: true,
    staff: true,
    student: false,
    contact: false,
  },
  {
    key: "hlt-004",
    name: "Wellbeing Check-In Follow-Up",
    description: "Sent after a pastoral check-in session with a student.",
    category: "Health & Wellbeing",
    enabled: true,
    staff: true,
    student: true,
    contact: false,
  },

  // Events & Activities
  {
    key: "evt-001",
    name: "School Event Announcement",
    description: "Announcement of an upcoming school-wide event or activity.",
    category: "Events & Activities",
    enabled: true,
    staff: true,
    student: true,
    contact: true,
  },
  {
    key: "evt-002",
    name: "Trip Consent Request",
    description: "Requests parental consent for a school trip or outing.",
    category: "Events & Activities",
    enabled: true,
    staff: false,
    student: false,
    contact: true,
  },
  {
    key: "evt-003",
    name: "Sports Team Selection",
    description:
      "Notifies a student they have been selected for a school team.",
    category: "Events & Activities",
    enabled: true,
    staff: false,
    student: true,
    contact: true,
  },
  {
    key: "evt-004",
    name: "Parent Evening Booking Confirmation",
    description: "Confirms parent/teacher meeting time and location.",
    category: "Events & Activities",
    enabled: true,
    staff: true,
    student: false,
    contact: true,
  },
  {
    key: "evt-005",
    name: "Club Sign-Up Confirmation",
    description: "Confirms enrolment in an after-school club or activity.",
    category: "Events & Activities",
    enabled: true,
    staff: false,
    student: true,
    contact: false,
  },

  // Admissions
  {
    key: "adm-001",
    name: "Application Received",
    description:
      "Acknowledgement that a new school application has been submitted.",
    category: "Admissions",
    enabled: true,
    staff: false,
    student: false,
    contact: true,
  },
  {
    key: "adm-002",
    name: "Offer of Place",
    description: "Formal offer of a school place to a prospective student.",
    category: "Admissions",
    enabled: true,
    staff: false,
    student: false,
    contact: true,
  },
  {
    key: "adm-003",
    name: "Enrolment Confirmation",
    description:
      "Confirms that enrolment documents have been received and processed.",
    category: "Admissions",
    enabled: true,
    staff: true,
    student: false,
    contact: true,
  },
  {
    key: "adm-004",
    name: "Waiting List Update",
    description:
      "Update on a student's position on the admissions waiting list.",
    category: "Admissions",
    enabled: true,
    staff: false,
    student: false,
    contact: true,
  },

  // Communication
  {
    key: "com-001",
    name: "Newsletter",
    description: "Periodic school newsletter sent to the whole community.",
    category: "Communication",
    enabled: true,
    staff: true,
    student: true,
    contact: true,
  },
  {
    key: "com-002",
    name: "Urgent School Announcement",
    description: "High-priority message (e.g. school closure, emergency).",
    category: "Communication",
    enabled: true,
    staff: true,
    student: true,
    contact: true,
  },
  {
    key: "com-003",
    name: "Class Change Notification",
    description:
      "Informs of a temporary or permanent change to a scheduled class.",
    category: "Communication",
    enabled: true,
    staff: true,
    student: true,
    contact: false,
  },
  {
    key: "com-004",
    name: "Teacher Message to Parent",
    description: "Direct message from a class teacher to a student's contacts.",
    category: "Communication",
    enabled: true,
    staff: false,
    student: false,
    contact: true,
  },

  // System & Admin
  {
    key: "sys-001",
    name: "Welcome — New Staff",
    description: "Onboarding email for a newly created staff account.",
    category: "System & Admin",
    enabled: true,
    staff: true,
    student: false,
    contact: false,
  },
  {
    key: "sys-002",
    name: "Welcome — New Student",
    description: "Onboarding email for a newly created student account.",
    category: "System & Admin",
    enabled: true,
    staff: false,
    student: true,
    contact: true,
  },
  {
    key: "sys-003",
    name: "Password Reset",
    description: "Secure link to reset account credentials.",
    category: "System & Admin",
    enabled: true,
    staff: true,
    student: true,
    contact: true,
  },
  {
    key: "sys-004",
    name: "Two-Factor Authentication Code",
    description: "One-time verification code for secure login.",
    category: "System & Admin",
    enabled: true,
    staff: true,
    student: true,
    contact: true,
  },
  {
    key: "sys-005",
    name: "Account Deactivation Notice",
    description: "Notification that a user account has been deactivated.",
    category: "System & Admin",
    enabled: true,
    staff: true,
    student: false,
    contact: false,
  },
  {
    key: "sys-006",
    name: "Data Export Ready",
    description: "Notifies admin when a requested data export is available.",
    category: "System & Admin",
    enabled: true,
    staff: true,
    student: false,
    contact: false,
  },

  // Reports
  {
    key: "rep-001",
    name: "End-of-Year Report",
    description:
      "Annual performance report covering all subjects and pastoral notes.",
    category: "Reports",
    enabled: true,
    staff: false,
    student: true,
    contact: true,
  },
  {
    key: "rep-002",
    name: "Mid-Term Progress Report",
    description: "Interim report giving a snapshot of academic progress.",
    category: "Reports",
    enabled: true,
    staff: false,
    student: true,
    contact: true,
  },
  {
    key: "rep-003",
    name: "Attendance Report (Monthly)",
    description: "Monthly attendance statistics sent to parents and admin.",
    category: "Reports",
    enabled: true,
    staff: true,
    student: false,
    contact: true,
  },
  {
    key: "rep-004",
    name: "Behaviour Summary Report",
    description: "Periodic summary of behaviour points and incidents.",
    category: "Reports",
    enabled: true,
    staff: true,
    student: false,
    contact: true,
  },
  {
    key: "rep-005",
    name: "Staff Performance Review",
    description: "Internal report shared with staff and line managers.",
    category: "Reports",
    enabled: true,
    staff: true,
    student: false,
    contact: false,
  },
];
